### ISSUE TITLE
enable wasi-c by default for releases

### ISSUE THREAD

**Issue by vapier** [CraneStation/wasmtime#396]
can the wasi-c functionality be enabled by default, at least for releases ?  the only way to experiment with `wasmtime --wasi-c` currently is by building wasmtime yourself from source which is a bit of a drag.  would be nice if the release prebuilts just included that.

**Comment by sunfishcode** [comment]
We disabled it by default in part because it uses `cmake` as a dependency, which turned out to be a noticeable for many people building Wasmtime. Also, disabling it makes our code footprint smaller; we don't usually need two WASI implementations. Can you say more about what you're looking to do here?

**Comment by kubkon** [comment]
I'm curious to see what you're after @vapier here as well :-)

**Comment by vapier** [comment]
i was experimenting with code that used `/dev/urandom` which the default runtime doesn't support.  i tried tracing the code a bit but couldn't see where it was going wrong.  the wasi-c runtime had no problem with it (the wasmtime-wasi-c/sandboxed-system-primitives/src/rights.h header has comments around RIGHTS_CHARACTER_DEVICE_BASE saying "grant all for now").

test case:
```c
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
int main(int argc, char *argv[])
{
	char *path = "/dev/urandom";
	if (argc > 1)
		path = argv[1];
	errno = 0;
	printf("open(%s) = %i (%i = %s)\n", path, open(path, O_RDONLY),
		errno, strerror(errno));
	return 0;
}
```

compiling with wasi-sdk-7.0:
```
$ ./wasi-sdk/bin/clang -Wall --sysroot=./wasi-sdk/share/wasi-sysroot test.c -o test.wasm
```

running with wasmtime-0.3.0:
```
$ wasmtime --dir=. --dir=/dev ./test.wasm /dev/null 
open(/dev/null) = 5 (0 = Success)
$ wasmtime --dir=. --dir=/dev ./test.wasm /dev/zero 
open(/dev/zero) = 5 (0 = Success)
$ wasmtime --dir=. --dir=/dev ./test.wasm /dev/full 
open(/dev/full) = 5 (0 = Success)
$ wasmtime --dir=. --dir=/dev ./test.wasm /dev/urandom 
open(/dev/urandom) = -1 (28 = Invalid argument)
$ wasmtime --dir=. --dir=/dev ./test.wasm /dev/random 
open(/dev/random) = -1 (28 = Invalid argument)
```

repeating with current master (e1b9c01d94485fa63d90920a10f49a3e9499f863) shows same behavior.  switching to --wasi-c makes it work.

i know that wasi-sdk includes the non-standard BSD arc4random APIs, but i don't want to go through projects and rewrite code to use them instead of `/dev/urandom` (or the Linux `getrandom` API).

**Comment by kubkon** [comment]
That's interesting. I cannot actually reproduce this error with the latest version of [wasi-common](https://github.com/CraneStation/wasi-common). Here's the output I'm getting:

```
$ target/release/wasmtime -d --dir=/dev test.wasm /dev/null
open(/dev/null) = 4 (0 = Success)

$ target/release/wasmtime -d --dir=/dev test.wasm /dev/random
open(/dev/random) = 4 (0 = Success)

$ target/release/wasmtime -d --dir=/dev test.wasm /dev/urandom
open(/dev/urandom) = 4 (0 = Success)
```

It seems that the version of `wasi-common` is somewhat outdated in `wasmtime` and that might just be the cause of the issue you've encountered. I've now submitted PR #398 which fast-forwards `wasmtime` to the latest `wasi-common` version. Could you do me a favour and after the PR lands in master, build `wasmtime` from source (without the `--wasi-c` flag) and see whether you're still getting an error?

**Comment by vapier** [comment]
i can give it another try once the PR goes through.  i'm not blocked on anything as i can continue experimenting with wasi-c.

i get that wasi-c requiring cmake/updated native compilers can be problematic for enabling it by default everywhere.  but i think that's a bit orthogonal to "should it be enabled in the default release binaries hosted here".  i have no idea where it's being built though (someone's workstation rather than the CI?).

wrt size, it doesn't seem to add that much unstripped ... adds (very) roughly ~1MB to wasmtime.  although i see the release prebuilts include debug info in them which balloons the size quite a lot (like 4x+).  i guess the current state of wasmtime is more on the "it's a developer preview" rather than "it's MVP" so shipping debug info directly isn't unreasonable.

**Comment by tschneidereit** [comment]
> i get that wasi-c requiring cmake/updated native compilers can be problematic for enabling it by default everywhere.

The bigger reason for not enabling it by default—or including it in our CI-built binaries—is that we want to remove it. Anything supported in wasi-c but not wasi-common is a bug in wasi-common, and by now there should be very few of these left, luckily.

Hopefully, your issue will be resolved once #398 lands! :)

**Comment by vapier** [comment]
if the overall goal is to replace wasi-c with wasi-common, that's good to know.  i started extending wasi-c, but i'll transition over to that.

**Comment by kubkon** [comment]
@vapier I've now merged #398 so if you could check if you can reproduce the error, that'd be great!

In terms of not having `wasi-c` baked in, in addition to what @sunfishcode and @tschneidereit already said, providing Windows support for `wasi-c` proved, well, to be problematic. Hence yet another reason why we're removing custom `build.rs` scripts in favour of the majority of the codebase written in Rust without any tricky C interops.

> if the overall goal is to replace wasi-c with wasi-common, that's good to know. i started extending wasi-c, but i'll transition over to that.

Please do! If you have any questions about the code organisation in `wasi-common`, you know, the "what, where, why", fire away and I'll do my best to help out as best as I can!

**Comment by vapier** [comment]
i ran `git pull --recurse` so i'm at daa3c3aeefc2633f563c2f485b13fee679e355e4.  then `cargo build` to update things.  still not happy though.  no idea what to check next.

```
$ RUST_LOG=trace ./target/debug/wasmtime -d --dir=. --dir=/dev ./test.wasm /dev/urandom
 DEBUG wasmtime_environ::cache::worker > Cache worker thread started.
 DEBUG wasmtime_environ::cache::worker > New nice value of worker thread: 3
 DEBUG wasmtime_environ::cache::config > Cache init("None"): CacheConfig {
    errors: [],
    enabled: true,
    directory: Some(
        "/home/vapier/.cache/wasmtime",
    ),
    worker_event_queue_size: Some(
        16,
    ),
    baseline_compression_level: Some(
        3,
    ),
    optimized_compression_level: Some(
        20,
    ),
    optimized_compression_usage_counter_threshold: Some(
        256,
    ),
    cleanup_interval: Some(
        3600s,
    ),
    optimizing_compression_task_timeout: Some(
        1800s,
    ),
    allowed_clock_drift_for_files_from_future: Some(
        86400s,
    ),
    file_count_soft_limit: Some(
        65536,
    ),
    files_total_size_soft_limit: Some(
        536870912,
    ),
    file_count_limit_percent_if_deleting: Some(
        70,
    ),
    files_total_size_limit_percent_if_deleting: Some(
        70,
    ),
}
 DEBUG cranelift_codegen::timing::details > timing: Starting Translate WASM module, (during <no pass>)
 DEBUG cranelift_codegen::timing::details > timing: Ending Translate WASM module
 TRACE wasmtime_environ::cache            > get_data() for path: /home/vapier/.cache/wasmtime/x86_64-unknown-linux-gnu/cranelift-e1b9c01d94485fa63d90920a10f49a3e9499f863-1570154157334/mod-OD6fNonRmbH0u3JQUxR7Gzwr8wFom6Uz-AyHxwmxYEQ
 TRACE wasmtime_environ::cache::worker    > handle_on_cache_get() for path: /home/vapier/.cache/wasmtime/x86_64-unknown-linux-gnu/cranelift-e1b9c01d94485fa63d90920a10f49a3e9499f863-1570154157334/mod-OD6fNonRmbH0u3JQUxR7Gzwr8wFom6Uz-AyHxwmxYEQ
 TRACE wasmtime_wasi::syscalls            > fd_prestat_get(fd=3, buf=0x11480)
 TRACE wasi_common::hostcalls_impl::fs    > fd_prestat_get(fd=3, prestat_ptr=0x11480)
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_prestat_dir_name(fd=3, path=0x200a0, path_len=1)
 TRACE wasi_common::hostcalls_impl::fs    > fd_prestat_dir_name(fd=3, path_ptr=0x200a0, path_len=1)
 TRACE wasi_common::hostcalls_impl::fs    >      | (path_ptr,path_len)='.'
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_fdstat_get(fd=3, buf=0x11468)
 TRACE wasi_common::hostcalls_impl::fs    > fd_fdstat_get(fd=3, fdstat_ptr=0x11468)
 TRACE wasi_common::hostcalls_impl::fs    >      | *buf=__wasi_fdstat_t { fs_filetype: 3, fs_flags: 0, fs_rights_base: 264240792, fs_rights_inheriting: 268435455 }
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_prestat_get(fd=4, buf=0x11480)
 TRACE wasi_common::hostcalls_impl::fs    > fd_prestat_get(fd=4, prestat_ptr=0x11480)
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_prestat_dir_name(fd=4, path=0x200a0, path_len=4)
 TRACE wasi_common::hostcalls_impl::fs    > fd_prestat_dir_name(fd=4, path_ptr=0x200a0, path_len=4)
 TRACE wasi_common::hostcalls_impl::fs    >      | (path_ptr,path_len)='/dev'
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_fdstat_get(fd=4, buf=0x11468)
 TRACE wasi_common::hostcalls_impl::fs    > fd_fdstat_get(fd=4, fdstat_ptr=0x11468)
 TRACE wasi_common::hostcalls_impl::fs    >      | *buf=__wasi_fdstat_t { fs_filetype: 3, fs_flags: 0, fs_rights_base: 264240792, fs_rights_inheriting: 268435455 }
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_prestat_get(fd=5, buf=0x11480)
 TRACE wasi_common::hostcalls_impl::fs    > fd_prestat_get(fd=5, prestat_ptr=0x11480)
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_EBADF
 TRACE wasmtime_wasi::syscalls            > environ_sizes_get(environ_count=0x11480, environ_buf_size=0x1148c)
 TRACE wasi_common::hostcalls_impl::misc  > environ_sizes_get(environ_count_ptr=0x11480, environ_size_ptr=0x1148c)
 TRACE wasi_common::hostcalls_impl::misc  >      | *environ_count_ptr=0
 TRACE wasi_common::hostcalls_impl::misc  >      | *environ_size_ptr=0
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > environ_get(environ=0x200a0, environ_buf=0x200d0)
 TRACE wasi_common::hostcalls_impl::misc  > environ_get(environ_ptr=0x200a0, environ_buf=0x200d0)
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > args_sizes_get(argc=0x1148c, argv_buf_size=0x11480)
 TRACE wasi_common::hostcalls_impl::misc  > args_sizes_get(argc_ptr=0x1148c, argv_buf_size_ptr=0x11480)
 TRACE wasi_common::hostcalls_impl::misc  >      | *argc_ptr=2
 TRACE wasi_common::hostcalls_impl::misc  >      | *argv_buf_size_ptr=23
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > args_get(argv=0x200e0, argv_buf=0x200f0)
 TRACE wasi_common::hostcalls_impl::misc  > args_get(argv_ptr=0x200e0, argv_buf=0x200f0)
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > fd_fdstat_get(fd=4, buf=0x11428)
 TRACE wasi_common::hostcalls_impl::fs    > fd_fdstat_get(fd=4, fdstat_ptr=0x11428)
 TRACE wasi_common::hostcalls_impl::fs    >      | *buf=__wasi_fdstat_t { fs_filetype: 3, fs_flags: 0, fs_rights_base: 264240792, fs_rights_inheriting: 268435455 }
 TRACE wasi_common::hostcalls             >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls            > path_open(dirfd=4, dirflags=1, path=0x200ff, path_len=7, oflags=0x0, fs_rights_base=0xfbffebe, fs_rights_inheriting=0xfffffff, fs_flags=0x0, fd=0x11424)
 TRACE wasi_common::hostcalls_impl::fs    > path_open(dirfd=4, dirflags=1, path_ptr=0x200ff, path_len=7, oflags=0x0, fs_rights_base=0xfbffebe, fs_rights_inheriting=0xfffffff, fs_flags=0x0, fd_out_ptr=0x11424)
 TRACE wasi_common::hostcalls_impl::fs    >      | (path_ptr,path_len)='urandom'
 DEBUG wasi_common::hostcalls_impl::fs_helpers > cur_path = "urandom"
 TRACE wasi_common::hostcalls                  >     -> errno=__WASI_EINVAL
 TRACE wasmtime_wasi::syscalls                 > fd_fdstat_get(fd=1, buf=0x10ff8)
 TRACE wasi_common::hostcalls_impl::fs         > fd_fdstat_get(fd=1, fdstat_ptr=0x10ff8)
 TRACE wasi_common::hostcalls                  >     -> errno=__WASI_EBADF
 TRACE wasmtime_wasi::syscalls                 > fd_write(fd=1, iovs=0x11000, iovs_len=2, nwritten=0x10ffc)
 TRACE wasi_common::hostcalls_impl::fs         > fd_write(fd=1, iovs_ptr=0x11000, iovs_len=2, nwritten=0x10ffc)
open(/dev/urandom) = -1 (28 = Invalid argument TRACE wasi_common::hostcalls_impl::fs         >      | *nwritten=46
 TRACE wasi_common::hostcalls                  >     -> errno=__WASI_ESUCCESS
 TRACE wasmtime_wasi::syscalls                 > fd_write(fd=1, iovs=0x11000, iovs_len=2, nwritten=0x10ffc)
 TRACE wasi_common::hostcalls_impl::fs         > fd_write(fd=1, iovs_ptr=0x11000, iovs_len=2, nwritten=0x10ffc)
)
 TRACE wasi_common::hostcalls_impl::fs         >      | *nwritten=2
 TRACE wasi_common::hostcalls                  >     -> errno=__WASI_ESUCCESS
```

snippet from strace:
```
fcntl(7, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
readlinkat(7, "urandom", 0x7ffc58e9358f, 4097) = -1 EINVAL (Invalid argument)
openat(7, "urandom", O_RDONLY|O_NOFOLLOW) = 8
close(7)                                = 0
fstat(8, {st_dev=makedev(0, 6), st_ino=1033, st_mode=S_IFCHR|0666, st_nlink=1, st_uid=65534, st_gid=65534, st_blksize=4096, st_blocks=0, st_rdev=makedev(1, 9), st_atime=2019-10-02T18:39:50-0400.615180139, st_mtime=2019-10-02T18:39:50-0400.615180139, st_ctime=2019-10-02T18:39:50-0400.615180139}) = 0
ioctl(8, TCGETS, 0x7ffc58e94fb0)        = -1 EINVAL (Invalid argument)
close(8)                                = 0
write(1, "open(/dev/urandom) = -1 (28 = In"..., 46open(/dev/urandom) = -1 (28 = Invalid argument) = 46
```
vs
```
fcntl(7, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
readlinkat(7, "null", 0x7ffffb0a4cbf, 4097) = -1 EINVAL (Invalid argument)
openat(7, "null", O_RDONLY|O_NOFOLLOW)  = 8
close(7)                                = 0
fstat(8, {st_dev=makedev(0, 6), st_ino=1028, st_mode=S_IFCHR|0666, st_nlink=1, st_uid=65534, st_gid=65534, st_blksize=4096, st_blocks=0, st_rdev=makedev(1, 3), st_atime=2019-10-02T18:39:50-0400.615180139, st_mtime=2019-10-02T18:39:50-0400.615180139, st_ctime=2019-10-02T18:39:50-0400.615180139}) = 0
ioctl(8, TCGETS, 0x7ffffb0a66e0)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(8, {st_dev=makedev(0, 6), st_ino=1028, st_mode=S_IFCHR|0666, st_nlink=1, st_uid=65534, st_gid=65534, st_blksize=4096, st_blocks=0, st_rdev=makedev(1, 3), st_atime=2019-10-02T18:39:50-0400.615180139, st_mtime=2019-10-02T18:39:50-0400.615180139, st_ctime=2019-10-02T18:39:50-0400.615180139}) = 0
ioctl(8, TCGETS, 0x7ffffb0a6500)        = -1 ENOTTY (Inappropriate ioctl for device)
fcntl(8, F_GETFL)                       = 0x28000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW)
write(1, "open(/dev/null) = 5 (0 = Success", 32open(/dev/null) = 5 (0 = Success) = 32
```

**Comment by bjorn3** [comment]
ioctl TCGETS for urandom gives EINVAL, while TCGETS for null gives ENOTTY.

**Comment by kubkon** [comment]
Hey @vapier! Sorry for not getting in touch earlier but I just got back from my travels. A quick update on my end, I believe I've managed to replicate your issue on my Linux box (running latest Arch distro), so fingers crossed this will lead me to the solution. Interestingly enough though, as I've posted earlier, I couldn't replicate the issue on my MacOS, so perhaps a hint lies somewhere there :-)

**Comment by kubkon** [comment]
I believe I've found the root cause of the issue and (hopefully) now fixed it in CraneStation/wasi-common#131. Just to sum up briefly, it turns out that the problem lied in our use of [nix]'s `nix::unistd::isatty` wrapper for `libc::isatty` syscall. [nix]'s implementation handles only `ENOTTY` as a signal for a valid file descriptor which is not a TTY, which indeed is as POSIX prescribes. However, on Linux, it seems that `EINVAL` is also used for that very purpose, which, in our implementation of `wasi-common` was treated only as an error, and hence, leading to the erroneous behaviour that you've uncovered (thanks for that BTW!).

When CraneStation/wasi-common#131 lands, I'll update the dependencies in `wasmtime` and let you know @vapier! :-)

[nix]: https://github.com/nix-rust/nix

**Comment by kubkon** [comment]
@vapier the fix should now be available if you compile `wasmtime` from source :-) I'd be much appreciated if you could check it out and verify that it indeed works for you as well! Also, thanks again for your bug report, it's been really helpful, and I hope you'll submit more of those should come across some additional bugs :-)

@tschneidereit how do we publish latest nightly `wasmtime` builds nowadays? Is it automated after every merged PR into upstream, or do we press some magic button? I'm asking cause it'd be good to have the latest fixes to `wasi-common` baked into latest nightly `wasmtime` build :-)

**Comment by bjorn3** [comment]
It gets build automatically: https://github.com/CraneStation/wasmtime/releases/tag/dev

**Comment by kubkon** [comment]
> It gets build automatically: https://github.com/CraneStation/wasmtime/releases/tag/dev

Ah, of course, now I see it. Thanks for pointing it out!
